version: "1.0"
services:
  api:
    build:
      context: ./
      dockerfile: "api_service/Dockerfile"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    network_mode: "host"
  stock:
    build:
      context: ./
      dockerfile: "stock_service/Dockerfile"
    ports:
      - "8001:8001"
    expose:
      - "8001"
    network_mode: "host"
